### ISSUE TITLE
Experiments about the Exercise dataset

### ISSUE THREAD

**Issue by chenbys** [Talegqz/unsupervised_co_part_segmentation#2]
Thanks for the excellent work again.

However, I wonder there is any released code or pretrained model about the Exercise dataset. 
In my experiments, it may be hard to achieve the performance.
If possible, please provide some configs, codes, and models on the Exercise dataset.
The undigested codes could be sent via e-mail (chen.bys@sjtu.edu.cn), and I will preserve and modify privately.

Thanks a lot for any help.

**Comment by Talegqz** [comment]
Our model on Exercise dataset has lost, because I left the lab where I did this work, and my data was deleted. In my memory, the configs is similar as TaiChiHD, and the most important, you should select the segmentation part in the result manually to match the annotation, just like the previous work.
What's more, you can sent me some results about your experiments through email (gaoqingzhe97@gmail.com) , and I am pleasure to provide some suggestions.

**Comment by chenbys** [comment]
Thanks. I will if necessary.
